<?xml version="1.0"?>
<Job name="Concat">

    <Parameter key="first" name="First">

        <CreateComponent>
            <![CDATA[
                def uiValue = ui.create(UIValue.class);
                uiValue.setConverter(new StringConverterString());
                return uiValue;
            ]]>
        </CreateComponent>

        <Validate>
            <![CDATA[
                return new NotEmptyStringValidator().validate(value);
            ]]>
        </Validate>

    </Parameter>

    <Parameter key="second" name="Second">

        <CreateComponent>
            <![CDATA[
                def uiValue = ui.create(UIValue.class);
                uiValue.setConverter(new StringConverterString());
                return uiValue;
            ]]>
        </CreateComponent>

        <Validate>
            <![CDATA[
                return new NotEmptyStringValidator().validate(value);
            ]]>
        </Validate>

    </Parameter>

    <Run>
        <![CDATA[
            return first + second
        ]]>
    </Run>
</Job>