<?xml version="1.0"?>
<Job id="concat" name="Concat" version="1.0.0">

    <Parameter key="first" name="First">
        <Validate>
            return new NotEmptyStringValidator().validate(value);
        </Validate>

    </Parameter>

    <Parameter key="second" name="Second">
        <Validate>
            return new NotEmptyStringValidator().validate(value);
        </Validate>
    </Parameter>

    <Run>
        return first + second
    </Run>
</Job>