<?xml version="1.0"?>
<Job id="simpleWithInternalCall" name="Simple with ext" version="1.0.0">

    <Parameter key="name" name="Name">

        <CreateComponent>
            def uiValue = ui.create(UIValue.class);
            uiValue.setConverter(new StringConverterString());
            uiValue.setDefaultValue("Enrico");
            return uiValue;
        </CreateComponent>

        <Validate>
            return new NotEmptyStringValidator().validate(values, value);
        </Validate>

    </Parameter>

    <Parameter key="surname" name="Surname">
        <CreateComponent>
            def uiValue = ui.create(UIValue.class);
            uiValue.setConverter(new StringConverterString());
            return uiValue;
        </CreateComponent>

        <Validate>
            return new NotEmptyStringValidator().validate(values, value);
        </Validate>

    </Parameter>

    <Call key="inv" name="Inv" project="this" job="concat">
        <Map in="name" out="first"/>
        <Map in="surname" out="second"/>
    </Call>

    <Run>
        return inv
    </Run>
    <!--Validate>
        return new NotEmptyStringValidator().validate(values, value);
    </Validate-->
</Job>