<?xml version="1.0"?>
<Job id="simple" name="Simple" version="1.0.0">

    <Parameter key="name" name="Name">
        <OnInit>
            component.setDefaultValue("Enrico");
        </OnInit>

        <Validate>
            return new NotEmptyStringValidator().validate(values, value);
        </Validate>

    </Parameter>

    <Parameter key="surname" name="Surname">
        <Validate>
            return new NotEmptyStringValidator().validate(values, value);
        </Validate>

    </Parameter>

    <Expression key="inv" name="Inv" dependsOn="name,surname">
        return Foo.concat(name, surname)
    </Expression>

    <Run>
        <![CDATA[
            return inv
        ]]>
    </Run>
    <!--Validate>
        return new NotEmptyStringValidator().validate(values, value);
    </Validate-->
</Job>