<?xml version="1.0"?>
<Job id="simpleWithExpression" name="Simple with expression" version="1.0.0">

    <Parameter key="name" name="Name">
        <OnInit>
            component.setDefaultValue("Enrico");
        </OnInit>

        <Validate>
            return new NotEmptyStringValidator().validate(values, value);
        </Validate>

    </Parameter>

    <Parameter key="surname" name="Surname">
        <Validate>
            return new NotEmptyStringValidator().validate(values, value);
        </Validate>
    </Parameter>

    <Expression key="completeName" name="Complete name" dependsOn="name,surname">
        return name + ' ' + surname;
    </Expression>

    <Run>
        return 'Mr. ' + completeName;
    </Run>
    <!--Validate>
        return new NotEmptyStringValidator().validate(values, value);
    </Validate-->
</Job>