<?xml version="1.0"?>
<Job id="simpleWithExternalCall" name="Simple with ext" version="1.0.0">

    <Parameter key="name" name="Name">

        <OnInit>
            component.setDefaultValue("Enrico");
        </OnInit>

        <Validate>
            return new NotEmptyStringValidator().validate(values, value);
        </Validate>

    </Parameter>

    <Parameter key="surname" name="Surname">
        <Validate>
            return new NotEmptyStringValidator().validate(values, value);
        </Validate>

    </Parameter>

    <Call key="inv" name="Inv" project="ext" job="concat">
        <Map in="name" out="first"/>
        <Map in="surname" out="second"/>
    </Call>

    <Run>
        return inv
    </Run>
    <!--Validate>
        return new NotEmptyStringValidator().validate(values, value);
    </Validate-->
</Job>