<?xml version="1.0"?>
<Job id="simple" name="Simple" version="1.0.0">

    <Parameter key="name" name="Name">

        <CreateComponent>
            def uiValue = ui.create(UIValue.class);
            uiValue.setConverter(new StringConverterString());
            uiValue.setDefaultValue("Enrico");
            return uiValue;
        </CreateComponent>

        <Validate>
            return new NotEmptyStringValidator().validate(values, value);
        </Validate>

    </Parameter>

    <Parameter key="surname" name="Surname">
        <CreateComponent>
            def uiValue = ui.create(UIValue.class);
            uiValue.setConverter(new StringConverterString());
            return uiValue;
        </CreateComponent>

        <Validate>
            return new NotEmptyStringValidator().validate(values, value);
        </Validate>

    </Parameter>

    <Expression key="inv" name="Inv" dependsOn="name,surname">
        <Evaluate>
            return Foo.concat(name, surname)
        </Evaluate>
    </Expression>

    <Run>
        <![CDATA[
            return inv
        ]]>
    </Run>
    <!--Validate>
        return new NotEmptyStringValidator().validate(values, value);
    </Validate-->
</Job>