<?xml version="1.0"?>
<Job name="Simple">

    <Parameter key="name" name="Name">

        <CreateComponent>
            def uiValue = ui.create(UIValue.class);
            uiValue.setConverter(new StringConverterString());
            uiValue.setDefaultValue("Enrico");
            return uiValue;
        </CreateComponent>

        <Validate>
            return new NotEmptyStringValidator().validate(value);
        </Validate>

    </Parameter>

    <Parameter key="surname" name="Surname">
        <CreateComponent>
            def uiValue = ui.create(UIValue.class);
            uiValue.setConverter(new StringConverterString());
            return uiValue;
        </CreateComponent>

        <Validate>
            return new NotEmptyStringValidator().validate(value);
        </Validate>

    </Parameter>
    <Parameter key="inv" name="Inv" visible="false">

        <CreateComponent>
            return ui.create(UIChoice.class);
        </CreateComponent>

        <Dependency key="name"/>
        <Dependency key="surname"/>

        <OnDependenciesChange>
            widget.getComponent().setItems([Foo.concat(name, surname)])
        </OnDependenciesChange>

    </Parameter>

    <Run>
        <![CDATA[
            return inv
        ]]>
    </Run>
    <!--Validate>
        return new NotEmptyStringValidator().validate(value);
    </Validate-->
</Job>